# Generated by Django 5.0.6 on 2024-05-24 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='login_info',
        ),
    ]
