# Generated by Django 5.0.6 on 2024-05-29 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_rename_login_login_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_info',
            name='login_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name='hospital_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('disease', models.CharField(max_length=100)),
                ('prescription', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.user_personal_info')),
            ],
        ),
        migrations.CreateModel(
            name='user_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_size', models.PositiveIntegerField(default=1)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.user_personal_info')),
            ],
        ),
        migrations.CreateModel(
            name='voice_ai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.user_personal_info')),
            ],
        ),
    ]
