# Generated by Django 5.0.6 on 2024-05-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_login_info_login_time_hospital_history_user_settings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_info',
            name='user_id',
            field=models.CharField(max_length=20),
        ),
    ]
