# Generated by Django 5.0.6 on 2024-05-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_alter_login_info_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily_intake_info',
            name='medication_id',
        ),
        migrations.AddField(
            model_name='daily_intake_info',
            name='user_id',
            field=models.CharField(default='test', max_length=20),
        ),
        migrations.AlterField(
            model_name='hospital_history',
            name='user_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='medication_info',
            name='user_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user_settings',
            name='user_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='voice_ai',
            name='user_id',
            field=models.CharField(max_length=20),
        ),
    ]
