# Generated by Django 5.0.6 on 2024-05-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_remove_daily_intake_info_medication_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_intake_info',
            name='medication',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
