# Generated by Django 5.0.6 on 2024-05-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_alter_voice_ai_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voice_ai',
            name='parameters',
            field=models.FileField(upload_to=''),
        ),
    ]
