# Generated by Django 5.0.6 on 2024-06-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_alter_voice_ai_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital_history',
            name='daily_intake',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
