# Generated by Django 5.0.6 on 2024-06-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_hospital_history_daily_intake'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital_history',
            name='duration',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
